# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glfw_config = debug
  glad_config = debug
  imgui_config = debug
  NebulaEngine_config = debug

else ifeq ($(config),release)
  glfw_config = release
  glad_config = release
  imgui_config = release
  NebulaEngine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glfw glad imgui NebulaEngine

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: glad glfw imgui

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C Nebula/ext/glfw -f Makefile config=$(glfw_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Nebula/ext/glad -f Makefile config=$(glad_config)
endif

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C Nebula/ext/imgui -f Makefile config=$(imgui_config)
endif

NebulaEngine: glfw glad imgui
ifneq (,$(NebulaEngine_config))
	@echo "==== Building NebulaEngine ($(NebulaEngine_config)) ===="
	@${MAKE} --no-print-directory -C . -f NebulaEngine.make config=$(NebulaEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C Nebula/ext/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Nebula/ext/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Nebula/ext/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C . -f NebulaEngine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw"
	@echo "   glad"
	@echo "   imgui"
	@echo "   NebulaEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"